---
title: "Tarea 10: Modelos de lenguaje"
output: html_document
---



## Unigramas

Haz los siguientes ejercicios usando el **modelo de unigramas**. Los ejercicios muestran por qué
es importante usar los símbolos de inicio-fin de frase.

Supón que solo hay dos palabras en nuestro vocabulario $a$ y $b$. Con probabilidad de ocurrencia en el 
languaje de $p_a=$ y $p_b$. 


1. Si no usamos símbolos de inicio y fin de frase, ¿cuánto suman las probabilidades de las frases tamaño 1 de este
vocabulario? (Supón que $p_a + p_b =1$). ¿cuánto suman las probabilidades de las frases de tamaño 2? 

- Hay dos frases de tamaño 1: "a" y "b". Por el modelo de unigramas, la probabilidad de "a" de $p_a$, la probabilidad
de $b$ es $p_b$, y suman 1.

$$P(a)=p_a, P(b) =p_b $$

cuya suma es 

$$(p_a + p_b)= 1$$


- Hay cuatro: "aa", "ab", "ba", "bb". Por unigramas

$$P(aa) = p_a^2, P(ab) = p_ap_b, P(ba)=p_ap_b, P(bb)=p_b^2$$
cuya suma es

$$(p_a + p_b)^2 = 1$$

2. Discute por qué por el inciso anteriores no podemos dar una distribución de probabilidad para frases
de longitud arbitraria bajo este modelo de unigramas.

- No suman 1 todas las probabilidades asignadas para todas las frases posibles (porque por ejemplo, las
de longitud 1 suman 1, las de longitud 2 suman 1, etc.)

Podemos tener una distribución $$P(N=n)$$

3. Supón que usamos símbolos de inicio $<s>$ y fin de frase $</s>$, 
¿cuánto suman las probabilidades de las frases de tamaño 1 de este vocabulario? (Supón que $p_a + p_b + p_{</s>}=1$) ¿cuánto suman las probabilidades de las frases tamaño 2? Podemos $p(<s>) = 1$ al inicio de frase.

- Frases de tamaño 1: $a</s>$, $b</s>$

$$P(<s>a</s>) = p_a p_f, P(<s>b</s>) =p_bp_f$$

cuya suma es:
$$ p_f (p_a + p_b) =p_f(1-p_f -p_i)$$
$$P(<s>aa</s>) = p_a^2 p_f, P(<s>ab</s>) =p_a p_b p_f, P(<s>ba</s>) =p_ap_bp_f, P(<s>bb</s>) =p_b^2 p_f$$

cuya suma es

$$p_f(p_a + p_b)^2 = p_f (1-p_f)^2$$


4. (Extra más difícil) Muestra que la suma de probabilidades sobre todas frases de longitud arbitraria es 1


- Frases de tamaño $k$, la suma es

$$p_f(1-p_f)^k$$

y su suma es

$$\sum_{k=1}^\infty p_f(1-p_f)^k = p_ f\sum_{k=0}^\infty(1-p_f)^k = p_f / p_f = 1$$

pero tenemos que contar también las frases de tamaño cero $</s>$ con probabilidad $p_f$.




## Bigramas

 (De nuestra referencia de Jurafsky). Considera el siguiente corpus:

```
<s> I am Sam </s>
<s> Sam I am </s>
<s> I am Sam </s>
<s> I do not like green eggs and Sam </s>
```

Con este corpus, 

5. Usa un modelo de bigramas (usando conteos) para calcular $P(Sam | am)$ y
$P(I | <s>)$. 

$$P(Sam | am) = \frac{N(am, Sam)}{N(am)} = \frac{2}{3} $$

$$P( I| <s>) = \frac{N(<s>, I)}{N(<s>)} = 3 / 4$$


6.  Usa el modelo de bigramas para calcular la probabilidad de la frase *I am Sam*

$$P(<s> I am Sam </s>) = P( I| <s>)  P(am|I) P(Sam|am) P(</s>|Sam) = 0.281$$

